VIA_ENABLE = yes
VIAL_ENABLE = yes

QMK_SETTINGS = yes
TAP_DANCE_ENABLE = yes
COMBO_ENABLE = yes

ENCODER_ENABLE = yes
ENCODER_MAP_ENABLE = yes
VIAL_ENCODERS_ENABLE = yes

VIALRGB_ENABLE = yes
RGB_MATRIX_ENABLE = yes
RGB_MATRIX_DRIVER = ws2812

VIAL_INSECURE = yes
#LTO_ENABLE = yes